#!/usr/bin/env python3
"""
Scaffold Mock Upstream API Generator
Generates ready-to-run mock servers in Node.js (zero-dep & Express), json-server, or Python FastAPI.
Default built-in pagination, rate limiting (429), latency simulation, and failure injection.
"""

import argparse
import json
import os
import random
import sys
import uuid
from datetime import datetime, timezone

def generate_sample_value(field_name: str, field_type: str, index: int):
    field_lower = field_name.lower()
    type_lower = field_type.lower()
    
    if "id" in field_lower and type_lower in ("uuid", "string"):
        return f"mock-{field_name}-{index + 1:04d}"
    if type_lower == "uuid":
        return str(uuid.uuid4())
    if type_lower in ("int", "integer", "number"):
        if "amount" in field_lower or "price" in field_lower:
            return round(10.0 + (index * 7.5) % 500, 2)
        if "count" in field_lower or "quantity" in field_lower:
            return (index * 3) % 50 + 1
        return index + 1
    if type_lower in ("float", "double"):
        return round(1.5 + (index * 0.75), 2)
    if type_lower in ("bool", "boolean"):
        return index % 2 == 0
    if type_lower in ("datetime", "timestamp", "date"):
        return datetime.fromtimestamp(1700000000 + (index * 86400), tz=timezone.utc).isoformat()
    if type_lower == "email" or "email" in field_lower:
        return f"user{index + 1}@example.com"
    if "name" in field_lower:
        first_names = ["Alex", "Jordan", "Taylor", "Morgan", "Sam", "Casey", "Riley", "Chris", "Jamie", "Pat"]
        return f"{first_names[index % len(first_names)]} {index + 1}"
    if "status" in field_lower:
        statuses = ["active", "pending", "completed", "archived", "failed"]
        return statuses[index % len(statuses)]
    if "role" in field_lower:
        roles = ["admin", "member", "viewer", "editor"]
        return roles[index % len(roles)]
    if "url" in field_lower:
        return f"https://api.example.com/{field_name}/{index + 1}"
    
    return f"sample_{field_name}_{index + 1}"

def parse_fields(fields_str: str):
    fields = {}
    if not fields_str:
        return {"id": "string", "name": "string", "status": "string", "createdAt": "datetime"}
    for item in fields_str.split(","):
        item = item.strip()
        if not item:
            continue
        if ":" in item:
            k, v = item.split(":", 1)
            fields[k.strip()] = v.strip()
        else:
            fields[item] = "string"
    return fields

def generate_seed_data(entity: str, fields: dict, count: int):
    items = []
    for i in range(count):
        row = {}
        for k, v in fields.items():
            row[k] = generate_sample_value(k, v, i)
        items.append(row)
    return items

def render_node_builtin(entity: str, items: list, port: int, rate_limit: int, rate_window: int):
    items_json = json.dumps(items, indent=2)
    return f"""// Zero-dependency Node.js Upstream Mock Server
// Auto-generated by mock-upstream-api scaffold
import http from 'node:http';
import url from 'node:url';

const PORT = process.env.PORT || {port};
const RATE_LIMIT_MAX = parseInt(process.env.RATE_LIMIT_MAX || '{rate_limit}', 10);
const RATE_LIMIT_WINDOW_MS = parseInt(process.env.RATE_LIMIT_WINDOW_MS || '{rate_window * 1000}', 10);
const DEFAULT_PAGE_SIZE = 10;

// In-Memory Seed Store
const items = {items_json};

// Sliding Window Rate Limiter State
const requestLogs = [];

function checkRateLimit(req, res) {{
  const now = Date.now();
  // Clean up expired entries
  while (requestLogs.length > 0 && requestLogs[0] <= now - RATE_LIMIT_WINDOW_MS) {{
    requestLogs.shift();
  }}

  const remaining = Math.max(0, RATE_LIMIT_MAX - requestLogs.length);
  const resetSec = Math.ceil((requestLogs.length > 0 ? (requestLogs[0] + RATE_LIMIT_WINDOW_MS - now) : RATE_LIMIT_WINDOW_MS) / 1000);

  res.setHeader('X-RateLimit-Limit', RATE_LIMIT_MAX);
  res.setHeader('X-RateLimit-Remaining', remaining);
  res.setHeader('X-RateLimit-Reset', resetSec);

  // Allow manual 429 simulation via header or query
  const force429 = req.headers['x-mock-status'] === '429';
  if (force429 || requestLogs.length >= RATE_LIMIT_MAX) {{
    res.setHeader('Retry-After', resetSec || 1);
    res.writeHead(429, {{ 'Content-Type': 'application/json' }});
    res.end(JSON.stringify({{
      error: 'Too Many Requests',
      message: 'Rate limit exceeded. Please back off and retry.',
      retry_after_seconds: resetSec || 1,
      limit: RATE_LIMIT_MAX,
      window_seconds: Math.round(RATE_LIMIT_WINDOW_MS / 1000)
    }}));
    return false;
  }}

  requestLogs.push(now);
  return true;
}}

const server = http.createServer(async (req, res) => {{
  const parsedUrl = url.parse(req.url, true);
  const pathname = parsedUrl.pathname.replace(/\\/+$/, '') || '/';
  const query = parsedUrl.query;

  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Mock-Status');

  if (req.method === 'OPTIONS') {{
    res.writeHead(204);
    res.end();
    return;
  }}

  // Rate Limiter Guard
  if (!checkRateLimit(req, res)) return;

  // Simulated Latency
  const delayMs = parseInt(query.delay || req.headers['x-mock-delay'] || '0', 10);
  if (delayMs > 0) {{
    await new Promise(resolve => setTimeout(resolve, delayMs));
  }}

  // Health check endpoint
  if (pathname === '/health') {{
    res.writeHead(200, {{ 'Content-Type': 'application/json' }});
    res.end(JSON.stringify({{ status: 'healthy', timestamp: new Date().toISOString() }}));
    return;
  }}

  // Collection endpoint: GET /api/{entity}s or /{entity}s
  const collectionPaths = ['/{entity}s', '/api/{entity}s', '/{entity}', '/api/{entity}'];
  if (collectionPaths.includes(pathname) && req.method === 'GET') {{
    // Pagination parameters (supports offset/limit, page/size, and cursor)
    let limit = parseInt(query.limit || query.size || DEFAULT_PAGE_SIZE, 10);
    limit = Math.min(Math.max(limit, 1), 100);

    let offset = 0;
    if (query.offset !== undefined) {{
      offset = Math.max(0, parseInt(query.offset, 10));
    }} else if (query.page !== undefined) {{
      const page = Math.max(1, parseInt(query.page, 10));
      offset = (page - 1) * limit;
    }} else if (query.cursor) {{
      try {{
        offset = parseInt(Buffer.from(query.cursor, 'base64').toString('ascii'), 10) || 0;
      }} catch (e) {{
        offset = 0;
      }}
    }}

    let filtered = [...items];
    // Filtering by status or search
    if (query.status) {{
      filtered = filtered.filter(i => String(i.status).toLowerCase() === String(query.status).toLowerCase());
    }}
    if (query.q) {{
      const q = String(query.q).toLowerCase();
      filtered = filtered.filter(i => JSON.stringify(i).toLowerCase().includes(q));
    }}

    const total = filtered.length;
    const paginated = filtered.slice(offset, offset + limit);
    const hasMore = offset + limit < total;
    const nextOffset = hasMore ? offset + limit : null;
    const nextCursor = nextOffset !== null ? Buffer.from(String(nextOffset)).toString('base64') : null;

    res.setHeader('X-Total-Count', total);
    res.setHeader('X-Has-More', hasMore ? 'true' : 'false');
    if (nextCursor) res.setHeader('X-Next-Cursor', nextCursor);

    res.writeHead(200, {{ 'Content-Type': 'application/json' }});
    res.end(JSON.stringify({{
      data: paginated,
      pagination: {{
        total,
        count: paginated.length,
        offset,
        limit,
        page: Math.floor(offset / limit) + 1,
        total_pages: Math.ceil(total / limit),
        has_more: hasMore,
        next_cursor: nextCursor
      }}
    }}));
    return;
  }}

  // Item by ID endpoint: GET /api/{entity}s/:id
  const match = pathname.match(new RegExp('^(?:/api)?/{entity}s?/([^/]+)$'));
  if (match && req.method === 'GET') {{
    const id = match[1];
    const item = items.find(i => String(i.id) === id);
    if (!item) {{
      res.writeHead(404, {{ 'Content-Type': 'application/json' }});
      res.end(JSON.stringify({{ error: 'Not Found', message: `Item with id ${{id}} not found` }}));
      return;
    }}
    res.writeHead(200, {{ 'Content-Type': 'application/json' }});
    res.end(JSON.stringify({{ data: item }}));
    return;
  }}

  res.writeHead(404, {{ 'Content-Type': 'application/json' }});
  res.end(JSON.stringify({{ error: 'Route Not Found', path: pathname }}));
}});

server.listen(PORT, () => {{
  console.log(`🚀 Mock Upstream API running on http://127.0.0.1:${{PORT}}`);
  console.log(`   Endpoint: GET http://127.0.0.1:${{PORT}}/api/{entity}s?page=1&limit=10`);
  console.log(`   Rate Limit: ${{RATE_LIMIT_MAX}} requests / ${{RATE_LIMIT_WINDOW_MS / 1000}}s`);
}});
"""

def render_express_js(entity: str, items: list, port: int, rate_limit: int, rate_window: int):
    items_json = json.dumps(items, indent=2)
    return f"""// Express.js Upstream Mock Server
// Auto-generated by mock-upstream-api scaffold
const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || {port};
const RATE_LIMIT_MAX = parseInt(process.env.RATE_LIMIT_MAX || '{rate_limit}', 10);
const RATE_LIMIT_WINDOW_MS = parseInt(process.env.RATE_LIMIT_WINDOW_MS || '{rate_window * 1000}', 10);

app.use(cors());
app.use(express.json());

// In-Memory Seed Store
const items = {items_json};

// Rate Limiter State
const requestLogs = [];

app.use((req, res, next) => {{
  const now = Date.now();
  while (requestLogs.length > 0 && requestLogs[0] <= now - RATE_LIMIT_WINDOW_MS) {{
    requestLogs.shift();
  }}

  const remaining = Math.max(0, RATE_LIMIT_MAX - requestLogs.length);
  const resetSec = Math.ceil((requestLogs.length > 0 ? (requestLogs[0] + RATE_LIMIT_WINDOW_MS - now) : RATE_LIMIT_WINDOW_MS) / 1000);

  res.setHeader('X-RateLimit-Limit', RATE_LIMIT_MAX);
  res.setHeader('X-RateLimit-Remaining', remaining);
  res.setHeader('X-RateLimit-Reset', resetSec);

  const force429 = req.headers['x-mock-status'] === '429' || req.query.simulate_429 === 'true';
  if (force429 || requestLogs.length >= RATE_LIMIT_MAX) {{
    res.setHeader('Retry-After', resetSec || 1);
    return res.status(429).json({{
      error: 'Too Many Requests',
      message: 'Rate limit exceeded. Please back off and retry.',
      retry_after_seconds: resetSec || 1,
      limit: RATE_LIMIT_MAX,
      window_seconds: Math.round(RATE_LIMIT_WINDOW_MS / 1000)
    }});
  }}

  requestLogs.push(now);
  next();
}});

// Simulated Latency Middleware
app.use(async (req, res, next) => {{
  const delayMs = parseInt(req.query.delay || req.headers['x-mock-delay'] || '0', 10);
  if (delayMs > 0) {{
    await new Promise(resolve => setTimeout(resolve, delayMs));
  }}
  next();
}});

// Health Check
app.get('/health', (req, res) => {{
  res.json({{ status: 'healthy', timestamp: new Date().toISOString() }});
}});

// GET /api/{entity}s or /{entity}s (Paginated)
app.get(['/{entity}s', '/api/{entity}s'], (req, res) => {{
  let limit = parseInt(req.query.limit || req.query.size || '10', 10);
  limit = Math.min(Math.max(limit, 1), 100);

  let offset = 0;
  if (req.query.offset !== undefined) {{
    offset = Math.max(0, parseInt(req.query.offset, 10));
  }} else if (req.query.page !== undefined) {{
    const page = Math.max(1, parseInt(req.query.page, 10));
    offset = (page - 1) * limit;
  }} else if (req.query.cursor) {{
    try {{
      offset = parseInt(Buffer.from(req.query.cursor, 'base64').toString('ascii'), 10) || 0;
    }} catch (e) {{
      offset = 0;
    }}
  }}

  let filtered = [...items];
  if (req.query.status) {{
    filtered = filtered.filter(i => String(i.status).toLowerCase() === String(req.query.status).toLowerCase());
  }}
  if (req.query.q) {{
    const q = String(req.query.q).toLowerCase();
    filtered = filtered.filter(i => JSON.stringify(i).toLowerCase().includes(q));
  }}

  const total = filtered.length;
  const paginated = filtered.slice(offset, offset + limit);
  const hasMore = offset + limit < total;
  const nextOffset = hasMore ? offset + limit : null;
  const nextCursor = nextOffset !== null ? Buffer.from(String(nextOffset)).toString('base64') : null;

  res.setHeader('X-Total-Count', total);
  res.setHeader('X-Has-More', hasMore ? 'true' : 'false');
  if (nextCursor) res.setHeader('X-Next-Cursor', nextCursor);

  res.json({{
    data: paginated,
    pagination: {{
      total,
      count: paginated.length,
      offset,
      limit,
      page: Math.floor(offset / limit) + 1,
      total_pages: Math.ceil(total / limit),
      has_more: hasMore,
      next_cursor: nextCursor
    }}
  }});
}});

// GET /api/{entity}s/:id
app.get(['/{entity}s/:id', '/api/{entity}s/:id'], (req, res) => {{
  const item = items.find(i => String(i.id) === req.params.id);
  if (!item) {{
    return res.status(404).json({{ error: 'Not Found', message: `Item ${{req.params.id}} not found` }});
  }}
  res.json({{ data: item }});
}});

app.listen(PORT, () => {{
  console.log(`🚀 Express Mock API running on http://127.0.0.1:${{PORT}}`);
  console.log(`   Endpoint: GET http://127.0.0.1:${{PORT}}/api/{entity}s?page=1&limit=10`);
}});
"""

def render_json_server_middleware(rate_limit: int, rate_window: int):
    return f"""// Custom middleware for json-server adding 429 rate limiting and pagination headers
const RATE_LIMIT_MAX = {rate_limit};
const RATE_LIMIT_WINDOW_MS = {rate_window * 1000};
const requestLogs = [];

module.exports = (req, res, next) => {{
  const now = Date.now();
  while (requestLogs.length > 0 && requestLogs[0] <= now - RATE_LIMIT_WINDOW_MS) {{
    requestLogs.shift();
  }}

  const remaining = Math.max(0, RATE_LIMIT_MAX - requestLogs.length);
  const resetSec = Math.ceil((requestLogs.length > 0 ? (requestLogs[0] + RATE_LIMIT_WINDOW_MS - now) : RATE_LIMIT_WINDOW_MS) / 1000);

  res.setHeader('X-RateLimit-Limit', RATE_LIMIT_MAX);
  res.setHeader('X-RateLimit-Remaining', remaining);
  res.setHeader('X-RateLimit-Reset', resetSec);

  const force429 = req.headers['x-mock-status'] === '429' || req.query.simulate_429 === 'true';
  if (force429 || requestLogs.length >= RATE_LIMIT_MAX) {{
    res.setHeader('Retry-After', resetSec || 1);
    return res.status(429).json({{
      error: 'Too Many Requests',
      message: 'Rate limit exceeded. Please back off and retry.',
      retry_after_seconds: resetSec || 1,
      limit: RATE_LIMIT_MAX,
      window_seconds: Math.round(RATE_LIMIT_WINDOW_MS / 1000)
    }});
  }}

  requestLogs.push(now);
  next();
}};
"""

def render_fastapi(entity: str, items: list, port: int, rate_limit: int, rate_window: int):
    items_json = json.dumps(items, indent=2)
    return f'''# Python FastAPI Upstream Mock Server
# Auto-generated by mock-upstream-api scaffold
import base64
import time
from typing import Optional, List, Any
from fastapi import FastAPI, HTTPException, Request, Response, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="Mock Upstream API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

RATE_LIMIT_MAX = {rate_limit}
RATE_LIMIT_WINDOW_SEC = {rate_window}
request_logs = []

ITEMS = {items_json}

@app.middleware("http")
async def rate_limit_and_latency_middleware(request: Request, call_next):
    now = time.time()
    global request_logs
    request_logs = [ts for ts in request_logs if ts > now - RATE_LIMIT_WINDOW_SEC]

    remaining = max(0, RATE_LIMIT_MAX - len(request_logs))
    reset_sec = int(RATE_LIMIT_WINDOW_SEC - (now - request_logs[0])) if request_logs else RATE_LIMIT_WINDOW_SEC

    # Check simulated delay
    delay_str = request.query_params.get("delay") or request.headers.get("x-mock-delay") or "0"
    try:
        delay = float(delay_str) / 1000.0
        if delay > 0:
            time.sleep(delay)
    except ValueError:
        pass

    force_429 = request.headers.get("x-mock-status") == "429" or request.query_params.get("simulate_429") == "true"
    if force_429 or len(request_logs) >= RATE_LIMIT_MAX:
        from fastapi.responses import JSONResponse
        headers = {{
            "X-RateLimit-Limit": str(RATE_LIMIT_MAX),
            "X-RateLimit-Remaining": "0",
            "X-RateLimit-Reset": str(max(1, reset_sec)),
            "Retry-After": str(max(1, reset_sec)),
        }}
        return JSONResponse(
            status_code=429,
            content={{
                "error": "Too Many Requests",
                "message": "Rate limit exceeded. Please back off and retry.",
                "retry_after_seconds": max(1, reset_sec),
                "limit": RATE_LIMIT_MAX,
                "window_seconds": RATE_LIMIT_WINDOW_SEC,
            }},
            headers=headers
        )

    request_logs.append(now)
    response = await call_next(request)
    response.headers["X-RateLimit-Limit"] = str(RATE_LIMIT_MAX)
    response.headers["X-RateLimit-Remaining"] = str(remaining)
    response.headers["X-RateLimit-Reset"] = str(max(1, reset_sec))
    return response

@app.get("/health")
def health():
    return {{"status": "healthy", "timestamp": time.time()}}

@app.get("/{entity}s")
@app.get("/api/{entity}s")
def list_items(
    page: Optional[int] = Query(None, ge=1),
    offset: Optional[int] = Query(None, ge=0),
    limit: int = Query(10, ge=1, le=100),
    cursor: Optional[str] = Query(None),
    status: Optional[str] = None,
    q: Optional[str] = None,
    response: Response = None
):
    calculated_offset = 0
    if offset is not None:
        calculated_offset = offset
    elif page is not None:
        calculated_offset = (page - 1) * limit
    elif cursor:
        try:
            calculated_offset = int(base64.b64decode(cursor.encode()).decode())
        except Exception:
            calculated_offset = 0

    filtered = ITEMS
    if status:
        filtered = [i for i in filtered if str(i.get("status", "")).lower() == status.lower()]
    if q:
        filtered = [i for i in filtered if q.lower() in str(i).lower()]

    total = len(filtered)
    paginated = filtered[calculated_offset : calculated_offset + limit]
    has_more = (calculated_offset + limit) < total
    next_offset = calculated_offset + limit if has_more else None
    next_cursor = base64.b64encode(str(next_offset).encode()).decode() if next_offset is not None else None

    if response:
        response.headers["X-Total-Count"] = str(total)
        response.headers["X-Has-More"] = "true" if has_more else "false"
        if next_cursor:
            response.headers["X-Next-Cursor"] = next_cursor

    return {{
        "data": paginated,
        "pagination": {{
            "total": total,
            "count": len(paginated),
            "offset": calculated_offset,
            "limit": limit,
            "page": (calculated_offset // limit) + 1,
            "total_pages": (total + limit - 1) // limit if limit > 0 else 1,
            "has_more": has_more,
            "next_cursor": next_cursor
        }}
    }}

@app.get("/{entity}s/{{item_id}}")
@app.get("/api/{entity}s/{{item_id}}")
def get_item(item_id: str):
    for item in ITEMS:
        if str(item.get("id")) == str(item_id):
            return {{"data": item}}
    raise HTTPException(status_code=404, detail=f"Item {{item_id}} not found")

if __name__ == "__main__":
    import uvicorn
    print(f"🚀 FastAPI Mock Server starting on http://127.0.0.1:{port}")
    uvicorn.run(app, host="127.0.0.1", port={port})
'''

def main():
    parser = argparse.ArgumentParser(description="Scaffold Mock Upstream API Server")
    parser.add_argument("--entity", default="item", help="Entity singular name (e.g. user, transaction, order)")
    parser.add_argument("--fields", default="", help="Comma-separated field:type pairs (e.g. id:uuid,name:string,email:string,status:string,amount:number,createdAt:datetime)")
    parser.add_argument("--schema", default="", help="Path to JSON file or schema to infer entity fields and items")
    parser.add_argument("--count", type=int, default=50, help="Number of mock items to seed (default: 50)")
    parser.add_argument("--port", type=int, default=4000, help="Server port (default: 4000)")
    parser.add_argument("--flavor", choices=["node-builtin", "express-js", "fastapi", "json-server"], default="node-builtin", help="Server framework flavor (default: node-builtin)")
    parser.add_argument("--rate-limit", type=int, default=10, help="Max requests allowed per window (default: 10)")
    parser.add_argument("--rate-window", type=int, default=10, help="Rate limit sliding window in seconds (default: 10)")
    parser.add_argument("--output", default="", help="Output file path (default: stdout or ./mock-server.<ext>)")

    args = parser.parse_args()

    # Load from schema file if provided
    items = []
    entity = args.entity.lower()
    if args.schema and os.path.exists(args.schema):
        with open(args.schema, 'r', encoding='utf-8') as f:
            raw_data = json.load(f)
            if isinstance(raw_data, list):
                items = raw_data
            elif isinstance(raw_data, dict):
                if "data" in raw_data and isinstance(raw_data["data"], list):
                    items = raw_data["data"]
                elif "items" in raw_data and isinstance(raw_data["items"], list):
                    items = raw_data["items"]
                else:
                    items = [raw_data]

    if not items:
        fields = parse_fields(args.fields)
        items = generate_seed_data(entity, fields, args.count)

    # Render target flavor
    content = ""
    default_filename = ""
    if args.flavor == "node-builtin":
        content = render_node_builtin(entity, items, args.port, args.rate_limit, args.rate_window)
        default_filename = "mock-server.mjs"
    elif args.flavor == "express-js":
        content = render_express_js(entity, items, args.port, args.rate_limit, args.rate_window)
        default_filename = "mock-server.js"
    elif args.flavor == "fastapi":
        content = render_fastapi(entity, items, args.port, args.rate_limit, args.rate_window)
        default_filename = "mock-server.py"
    elif args.flavor == "json-server":
        db_payload = {f"{entity}s": items}
        mw_content = render_json_server_middleware(args.rate_limit, args.rate_window)
        if args.output:
            out_dir = args.output if os.path.isdir(args.output) else os.path.dirname(args.output) or "."
            os.makedirs(out_dir, exist_ok=True)
            with open(os.path.join(out_dir, "db.json"), "w", encoding="utf-8") as f:
                json.dump(db_payload, f, indent=2)
            with open(os.path.join(out_dir, "middleware.js"), "w", encoding="utf-8") as f:
                f.write(mw_content)
            print(f"Wrote {os.path.join(out_dir, 'db.json')} and {os.path.join(out_dir, 'middleware.js')}")
            return
        else:
            print(json.dumps(db_payload, indent=2))
            return

    if args.output:
        out_path = args.output
        if os.path.isdir(out_path):
            out_path = os.path.join(out_path, default_filename)
        os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✅ Generated {args.flavor} mock server -> {out_path}")
    else:
        sys.stdout.write(content)

if __name__ == "__main__":
    main()
